// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjkXXCf5euXxVTWzbfkcCJf-4lga8vZxI',
    appId: '1:42155495380:web:7f0de647894bb85bcf9041',
    messagingSenderId: '42155495380',
    projectId: 'fluterweb01',
    authDomain: 'fluterweb01.firebaseapp.com',
    storageBucket: 'fluterweb01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoXUStLd_72QgQ1hL3Brw5mz3SYPjl1FU',
    appId: '1:42155495380:android:1b8877b52122b3decf9041',
    messagingSenderId: '42155495380',
    projectId: 'fluterweb01',
    storageBucket: 'fluterweb01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD06cnPDuXIa8vqBSoY8v9D0eHglswfHsc',
    appId: '1:42155495380:ios:f492657f498b1d33cf9041',
    messagingSenderId: '42155495380',
    projectId: 'fluterweb01',
    storageBucket: 'fluterweb01.firebasestorage.app',
    iosClientId: '42155495380-3foaroa8i9k19ba60afmght57o5ngjl0.apps.googleusercontent.com',
    iosBundleId: 'pt.tony.primeiroProjeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD06cnPDuXIa8vqBSoY8v9D0eHglswfHsc',
    appId: '1:42155495380:ios:f492657f498b1d33cf9041',
    messagingSenderId: '42155495380',
    projectId: 'fluterweb01',
    storageBucket: 'fluterweb01.firebasestorage.app',
    iosClientId: '42155495380-3foaroa8i9k19ba60afmght57o5ngjl0.apps.googleusercontent.com',
    iosBundleId: 'pt.tony.primeiroProjeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjkXXCf5euXxVTWzbfkcCJf-4lga8vZxI',
    appId: '1:42155495380:web:7f0de647894bb85bcf9041',
    messagingSenderId: '42155495380',
    projectId: 'fluterweb01',
    authDomain: 'fluterweb01.firebaseapp.com',
    storageBucket: 'fluterweb01.firebasestorage.app',
  );

}